on:
    push:
    workflow_dispatch:

jobs:
    tests:
        runs-on: windows
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-dotnet@v4
              with: 
                dotnet-version: 8.0.x
            - run: cd ChatWsTest && dotnet test
